version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

    # Backend Service
  backend:
    build: ./backend-repo/backend
    container_name: backend
    ports:
      - "5000:5000"
    # Uses the ENV from Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

    # Frontend Service
  frontend:
    build: ./frontend-repo/frontend
    container_name: frontend
    ports:
      - "4545:3000"
    depends_on:
      - backend
